### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by VamshiVerma** [swiftyspiffy/OpenWeatherMap-API-CSharp#1]
Please, provide installation steps for the VS.

**Comment by swiftyspiffy** [comment]
This project isn't really maintained and there isn't a NuGet package available for it.
To use it, you will need to:
1. Clone repo to your computer.
2. Open project file and build project
3. Reference the built .DLL file in your project.
4. Access it in your code.

**Comment by pluczak99** [comment]
The project isn't making accessing OpenWeatherMap API as easy as explained above. I am sure it works beautifully in your environment, but phrasing a step as "Access it in your code" is so vague, it requires a lot of extra code to ensure it can be used. For once, I have an issue with utilizing Java-based naming convention, like "JToken", "JObject" etc. Another thing is you could have included a 2nd Console app solution as part of the example, instead of the Step 4's actual meaning "figure out how to use it in your C# app". 

Well, if the project "isn't really maintained" and furthermore, "there isn't a NuGet package available for it", what is the exact reason for making your unusable library public on GitHub? Do the right thing and remove the project, because simply it is not at the quality level to share it beyond your own development team.

**Comment by swiftyspiffy** [comment]
Despite your entitlement and nonsensical rambling, I’ll update this just for you in a few hours.

In the future, no one is forcing you to use anything. I’m sure there’s a billion of these libraries around, choose a different one.

**Comment by swiftyspiffy** [comment]
And for what it’s worth, there’s like 1 public function in this whole library so “access it in your code” isn’t exactly hand wavy or disingenuous.

Additionally, JToken and JObject are models objects from Newtonsoft json, which is the most downloaded json library (and most downloaded nugget package?) in the community. It’s not something I came up with.

**Comment by eprenn** [comment]
Based

**Comment by swiftyspiffy** [comment]
Closing. Reopen if needed.
